### ISSUE TITLE
5.8 Support Problem

### ISSUE THREAD

**Issue by alisalehiman** [GeneaLabs/laravel-maps#10]
installation request for laravel/framework (locked at v5.8.4, required as 5.8.*) -> satisfiable by laravel/framework[v5.8.4].

**Comment by mikebronner** [comment]
@alisalehiman Thanks, I will get this updated soon.

**Comment by charlie00788** [comment]
Installation request for laravel/framework (locked at v5.8.11, required as 5.8.*) -> satisfiable by laravel/framework[v5.8.11].

**Comment by mikebronner** [comment]
I have not been able to replicate this issue. This is probably caused by another package. Please post your entire composer output.

**Comment by mikebronner** [comment]
Dependency constraints have been updated to require at a minimum Laravel 6.0.
