### ISSUE TITLE
Is it possible to generate static map?

### ISSUE THREAD

**Issue by dinajpuri** [GeneaLabs/laravel-maps#2]
Hi,

I've used this fine package before. Now I also need to generate static map and save the image..
Could you pls give me some hint how I can do it.

Regards

**Comment by mikebronner** [comment]
I'm not sure this is possible at the moment. I have saved images that were created in `<canvas></canvas>` objects before. I would recommend looking at an image library that can save the content of a DOM node as an image, maybe something like this one: https://github.com/tsayen/dom-to-image.

Please to report back if you are able to find a solution. I am closing this for now, though, as it is out of the scope of this package. :) Thanks for asking the question, though, it is definitely an interesting one!
