### ISSUE TITLE
Cannot install on laravel 5.8.35

### ISSUE THREAD

**Issue by CristianEstiber** [GeneaLabs/laravel-maps#21]
> Using version ^0.6.1 for genealabs/laravel-maps
> ./composer.json has been updated
> Loading composer repositories with package information
> Updating dependencies (including require-dev)
> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - Installation request for genealabs/laravel-maps ^0.6.1 -> satisfiable by genealabs/laravel-maps[0.6.1].
>     - Conclusion: remove laravel/framework v5.8.35
>     - Conclusion: don't install laravel/framework v5.8.35
>     - genealabs/laravel-maps 0.6.1 requires illuminate/support ^6.0 -> satisfiab
> le by illuminate/support[6.x-dev, v6.0.0, v6.0.1, v6.0.2, v6.0.3, v6.0.4, v6.1.0
> , v6.2.0, v6.3.0, v6.4.1, v6.5.0, v6.5.1, v6.5.2, v6.6.0].
>     - don't install illuminate/support 6.x-dev|don't install laravel/framework v
> 5.8.35
>     - don't install illuminate/support v6.0.0|don't install laravel/framework v5
> .8.35
>     - don't install illuminate/support v6.0.1|don't install laravel/framework v5
> .8.35
>     - don't install illuminate/support v6.0.2|don't install laravel/framework v5
> .8.35
>     - don't install illuminate/support v6.0.3|don't install laravel/framework v5
> .8.35
>     - don't install illuminate/support v6.0.4|don't install laravel/framework v5
> .8.35
>     - don't install illuminate/support v6.1.0|don't install laravel/framework v5
> .8.35
>     - don't install illuminate/support v6.2.0|don't install laravel/framework v5
> .8.35
>     - don't install illuminate/support v6.3.0|don't install laravel/framework v5
> .8.35
>     - don't install illuminate/support v6.4.1|don't install laravel/framework v5
> .8.35
>     - don't install illuminate/support v6.5.0|don't install laravel/framework v5
> .8.35
>     - don't install illuminate/support v6.5.1|don't install laravel/framework v5
> .8.35
>     - don't install illuminate/support v6.5.2|don't install laravel/framework v5
> .8.35
>     - don't install illuminate/support v6.6.0|don't install laravel/framework v5
> .8.35
>     - Installation request for laravel/framework (locked at v5.8.35, required as
>  5.8.*) -> satisfiable by laravel/framework[v5.8.35].
> 
> 
> Installation failed, reverting ./composer.json to its original content.

**Comment by mikebronner** [comment]
I no longer support Laravel 5.8, sorry.
