### ISSUE TITLE
Places Input Autocomplete Not Working

### ISSUE THREAD

**Issue by Zolak94** [GeneaLabs/laravel-maps#8]
I've put everything same as on the BIOINSTALL website, just changed to facade Map:: where i should, but that option is not working, it's not auto completing anything that I type.

**Comment by mikebronner** [comment]
Places input field has nothing to do with this package. This package is for rendering out maps where you already have data for the map. The places auto-complete input field is a client-side feature that you will have to implement with Google's Javascript library directly. :) Good luck!
